/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './layouts/**/*.htm',
    './pages/**/*.htm',
    './partials/**/*.htm',
    './assets/src/js/**/*.js',
  ],
  safelist: [
    // DaisyUI components
    'btn', 'btn-primary', 'btn-secondary', 'btn-accent', 'btn-ghost', 'btn-link', 'btn-outline',
    'btn-active', 'btn-disabled', 'btn-lg', 'btn-md', 'btn-sm', 'btn-xs', 'btn-wide', 'btn-block',
    'btn-circle', 'btn-square', 'btn-success', 'btn-warning', 'btn-error', 'btn-info',
    'card', 'card-body', 'card-title', 'card-actions', 'card-compact', 'card-normal', 'card-side',
    'alert', 'alert-info', 'alert-success', 'alert-warning', 'alert-error',
    'badge', 'badge-primary', 'badge-secondary', 'badge-accent', 'badge-ghost', 'badge-outline',
    'badge-lg', 'badge-md', 'badge-sm', 'badge-xs',
    'tabs', 'tab', 'tab-active', 'tab-disabled', 'tab-lifted', 'tab-boxed', 'tabs-boxed',
    'modal', 'modal-open', 'modal-box', 'modal-action', 'modal-backdrop', 'modal-toggle',
    'dropdown', 'dropdown-content', 'dropdown-open', 'dropdown-top', 'dropdown-bottom',
    'dropdown-left', 'dropdown-right', 'dropdown-end', 'dropdown-hover',
    'menu', 'menu-title', 'menu-dropdown', 'menu-dropdown-toggle', 'menu-dropdown-show',
    'navbar', 'navbar-start', 'navbar-center', 'navbar-end',
    'footer', 'footer-title', 'footer-center',
    'hero', 'hero-content', 'hero-overlay',
    'form-control', 'label', 'label-text', 'label-text-alt',
    'input', 'input-bordered', 'input-ghost', 'input-primary', 'input-secondary', 'input-accent',
    'input-info', 'input-success', 'input-warning', 'input-error',
    'input-lg', 'input-md', 'input-sm', 'input-xs',
    'textarea', 'textarea-bordered', 'textarea-ghost', 'textarea-primary', 'textarea-secondary',
    'textarea-accent', 'textarea-info', 'textarea-success', 'textarea-warning', 'textarea-error',
    'textarea-lg', 'textarea-md', 'textarea-sm', 'textarea-xs',
    'select', 'select-bordered', 'select-ghost', 'select-primary', 'select-secondary',
    'select-accent', 'select-info', 'select-success', 'select-warning', 'select-error',
    'select-lg', 'select-md', 'select-sm', 'select-xs',
    'checkbox', 'checkbox-primary', 'checkbox-secondary', 'checkbox-accent',
    'checkbox-success', 'checkbox-warning', 'checkbox-error', 'checkbox-info',
    'checkbox-lg', 'checkbox-md', 'checkbox-sm', 'checkbox-xs',
    'radio', 'radio-primary', 'radio-secondary', 'radio-accent',
    'radio-success', 'radio-warning', 'radio-error', 'radio-info',
    'radio-lg', 'radio-md', 'radio-sm', 'radio-xs',
    'toggle', 'toggle-primary', 'toggle-secondary', 'toggle-accent',
    'toggle-success', 'toggle-warning', 'toggle-error', 'toggle-info',
    'toggle-lg', 'toggle-md', 'toggle-sm', 'toggle-xs',
    'range', 'range-primary', 'range-secondary', 'range-accent',
    'range-success', 'range-warning', 'range-error', 'range-info',
    'range-lg', 'range-md', 'range-sm', 'range-xs',
    'file-input', 'file-input-bordered', 'file-input-ghost',
    'file-input-primary', 'file-input-secondary', 'file-input-accent',
    'file-input-info', 'file-input-success', 'file-input-warning', 'file-input-error',
    'file-input-lg', 'file-input-md', 'file-input-sm', 'file-input-xs',
    'progress', 'progress-primary', 'progress-secondary', 'progress-accent',
    'progress-info', 'progress-success', 'progress-warning', 'progress-error',
    'radial-progress',
    'loading', 'loading-spinner', 'loading-dots', 'loading-ring', 'loading-ball', 'loading-bars',
    'loading-infinity', 'loading-lg', 'loading-md', 'loading-sm', 'loading-xs',
    'tooltip', 'tooltip-open', 'tooltip-top', 'tooltip-bottom', 'tooltip-left', 'tooltip-right',
    'tooltip-primary', 'tooltip-secondary', 'tooltip-accent', 'tooltip-info',
    'tooltip-success', 'tooltip-warning', 'tooltip-error',
    'swap', 'swap-active', 'swap-rotate', 'swap-flip',
    'avatar', 'avatar-group', 'online', 'offline',
    'divider', 'divider-vertical', 'divider-horizontal',
    'kbd', 'kbd-lg', 'kbd-md', 'kbd-sm', 'kbd-xs',
    'stat', 'stat-title', 'stat-value', 'stat-desc', 'stat-figure', 'stat-actions', 'stats',
    'stats-horizontal', 'stats-vertical',
    'table', 'table-zebra', 'table-pin-rows', 'table-pin-cols', 'table-xs', 'table-sm',
    'table-md', 'table-lg',
    'timeline', 'timeline-start', 'timeline-middle', 'timeline-end', 'timeline-box',
    'toast', 'toast-top', 'toast-middle', 'toast-bottom', 'toast-start', 'toast-center', 'toast-end',
    'breadcrumbs',
    'link', 'link-primary', 'link-secondary', 'link-accent', 'link-neutral',
    'link-success', 'link-warning', 'link-error', 'link-info', 'link-hover',
    'steps', 'step', 'step-primary', 'step-secondary', 'step-accent',
    'step-info', 'step-success', 'step-warning', 'step-error',
    'steps-vertical', 'steps-horizontal',
    'collapse', 'collapse-title', 'collapse-content', 'collapse-arrow', 'collapse-plus',
    'collapse-open', 'collapse-close',
    'carousel', 'carousel-item', 'carousel-center', 'carousel-end', 'carousel-vertical',
    'indicator', 'indicator-item', 'indicator-start', 'indicator-center', 'indicator-end',
    'indicator-top', 'indicator-middle', 'indicator-bottom',
    'mockup-phone', 'mockup-browser', 'mockup-window', 'mockup-code',
    'artboard', 'phone-1', 'phone-2', 'phone-3', 'phone-4', 'phone-5', 'phone-6',
    'stack',
    'glass',
    'join', 'join-item', 'join-horizontal', 'join-vertical',
    'mask', 'mask-circle', 'mask-squircle', 'mask-heart', 'mask-hexagon', 'mask-hexagon-2',
    'mask-decagon', 'mask-pentagon', 'mask-diamond', 'mask-square', 'mask-star', 'mask-star-2',
    'mask-triangle', 'mask-triangle-2', 'mask-triangle-3', 'mask-triangle-4', 'mask-parallelogram',
    'mask-parallelogram-2', 'mask-parallelogram-3', 'mask-parallelogram-4',
    // Background gradients y CSS variables
    {
      pattern: /^bg-gradient-to-(r|l|t|b|tr|tl|br|bl)$/,
    },
    {
      pattern: /^from-(base-100|base-200|base-300|primary|secondary|accent|neutral|info|success|warning|error)$/,
    },
    {
      pattern: /^to-(base-100|base-200|base-300|primary|secondary|accent|neutral|info|success|warning|error|transparent)$/,
    },
    {
      pattern: /^via-(base-100|base-200|base-300|primary|secondary|accent|neutral|info|success|warning|error)$/,
    },
    // Text colors with DaisyUI
    {
      pattern: /^text-(base-content|primary|secondary|accent|neutral|info|success|warning|error)$/,
    },
    // Background colors with DaisyUI
    {
      pattern: /^bg-(base-100|base-200|base-300|primary|secondary|accent|neutral|info|success|warning|error)$/,
    },
    // Border colors with DaisyUI
    {
      pattern: /^border-(base-100|base-200|base-300|primary|secondary|accent|neutral|info|success|warning|error)$/,
    },
    // Responsive text sizes
    'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl', 'text-6xl',
    'sm:text-xs', 'sm:text-sm', 'sm:text-base', 'sm:text-lg', 'sm:text-xl', 'sm:text-2xl', 'sm:text-3xl', 'sm:text-4xl',
    'md:text-xs', 'md:text-sm', 'md:text-base', 'md:text-lg', 'md:text-xl', 'md:text-2xl', 'md:text-3xl', 'md:text-4xl',
    'lg:text-xs', 'lg:text-sm', 'lg:text-base', 'lg:text-lg', 'lg:text-xl', 'lg:text-2xl', 'lg:text-3xl', 'lg:text-4xl',
    'xl:text-xs', 'xl:text-sm', 'xl:text-base', 'xl:text-lg', 'xl:text-xl', 'xl:text-2xl', 'xl:text-3xl', 'xl:text-4xl',
    // Responsive spacing
    'p-0', 'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-8', 'p-10', 'p-12', 'p-16', 'p-20', 'p-24',
    'sm:p-0', 'sm:p-1', 'sm:p-2', 'sm:p-3', 'sm:p-4', 'sm:p-5', 'sm:p-6', 'sm:p-8', 'sm:p-10', 'sm:p-12',
    'md:p-0', 'md:p-1', 'md:p-2', 'md:p-3', 'md:p-4', 'md:p-5', 'md:p-6', 'md:p-8', 'md:p-10', 'md:p-12',
    'lg:p-0', 'lg:p-1', 'lg:p-2', 'lg:p-3', 'lg:p-4', 'lg:p-5', 'lg:p-6', 'lg:p-8', 'lg:p-10', 'lg:p-12',
    'xl:p-0', 'xl:p-1', 'xl:p-2', 'xl:p-3', 'xl:p-4', 'xl:p-5', 'xl:p-6', 'xl:p-8', 'xl:p-10', 'xl:p-12',
    // Responsive margins
    'm-0', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-8', 'm-10', 'm-12', 'm-16', 'm-20', 'm-24',
    'sm:m-0', 'sm:m-1', 'sm:m-2', 'sm:m-3', 'sm:m-4', 'sm:m-5', 'sm:m-6', 'sm:m-8', 'sm:m-10', 'sm:m-12',
    'md:m-0', 'md:m-1', 'md:m-2', 'md:m-3', 'md:m-4', 'md:m-5', 'md:m-6', 'md:m-8', 'md:m-10', 'md:m-12',
    'lg:m-0', 'lg:m-1', 'lg:m-2', 'lg:m-3', 'lg:m-4', 'lg:m-5', 'lg:m-6', 'lg:m-8', 'lg:m-10', 'lg:m-12',
    'xl:m-0', 'xl:m-1', 'xl:m-2', 'xl:m-3', 'xl:m-4', 'xl:m-5', 'xl:m-6', 'xl:m-8', 'xl:m-10', 'xl:m-12',
    // Responsive display
    'block', 'inline', 'inline-block', 'flex', 'inline-flex', 'grid', 'hidden',
    'sm:block', 'sm:inline', 'sm:inline-block', 'sm:flex', 'sm:inline-flex', 'sm:grid', 'sm:hidden',
    'md:block', 'md:inline', 'md:inline-block', 'md:flex', 'md:inline-flex', 'md:grid', 'md:hidden',
    'lg:block', 'lg:inline', 'lg:inline-block', 'lg:flex', 'lg:inline-flex', 'lg:grid', 'lg:hidden',
    'xl:block', 'xl:inline', 'xl:inline-block', 'xl:flex', 'xl:inline-flex', 'xl:grid', 'xl:hidden',
    // Responsive grid
    'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5', 'grid-cols-6', 'grid-cols-12',
    'sm:grid-cols-1', 'sm:grid-cols-2', 'sm:grid-cols-3', 'sm:grid-cols-4', 'sm:grid-cols-5', 'sm:grid-cols-6',
    'md:grid-cols-1', 'md:grid-cols-2', 'md:grid-cols-3', 'md:grid-cols-4', 'md:grid-cols-5', 'md:grid-cols-6',
    'lg:grid-cols-1', 'lg:grid-cols-2', 'lg:grid-cols-3', 'lg:grid-cols-4', 'lg:grid-cols-5', 'lg:grid-cols-6',
    'xl:grid-cols-1', 'xl:grid-cols-2', 'xl:grid-cols-3', 'xl:grid-cols-4', 'xl:grid-cols-5', 'xl:grid-cols-6',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#f0f9ff',
          100: '#e0f2fe',
          200: '#bae6fd',
          300: '#7dd3fc',
          400: '#38bdf8',
          500: '#0ea5e9',
          600: '#0284c7',
          700: '#0369a1',
          800: '#075985',
          900: '#0c4a6e',
          950: '#082f49',
        },
        secondary: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
          950: '#020617',
        },
      },
      fontFamily: {
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
        serif: ['Prompt', 'Georgia', 'serif'],
        heading: ['Prompt', 'Georgia', 'serif'],
        prompt: ['Prompt', 'Georgia', 'serif'],
      },
      fontSize: {
        'xs': ['0.75rem', { lineHeight: '1rem' }],
        'sm': ['0.875rem', { lineHeight: '1.375rem' }],
        'base': ['1rem', { lineHeight: '1.625rem' }],
        'lg': ['1.125rem', { lineHeight: '1.875rem' }],
        'xl': ['1.25rem', { lineHeight: '2rem' }],
        '2xl': ['1.5rem', { lineHeight: '2.25rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.5rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.875rem' }],
        '5xl': ['3rem', { lineHeight: '3.5rem' }],
        '6xl': ['3.75rem', { lineHeight: '4.25rem' }],
        '7xl': ['4.5rem', { lineHeight: '5rem' }],
        '8xl': ['6rem', { lineHeight: '6.5rem' }],
        '9xl': ['8rem', { lineHeight: '8.5rem' }],
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '128': '32rem',
        '144': '36rem',
      },
      borderRadius: {
        'none': '0',
        'sm': '0.375rem',
        'DEFAULT': '0.5rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.75rem',
        'full': '9999px',
      },
      minHeight: {
        '12': '3rem',
        '14': '3.5rem',
        '16': '4rem',
      },
      screens: {
        'xs': '475px',
        '3xl': '1600px',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'fade-out': 'fadeOut 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'bounce-in': 'bounceIn 0.6s ease-out',
        'zoom-in': 'zoomIn 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideUp: {
          '0%': { transform: 'translateY(100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(0)' },
        },
        bounceIn: {
          '0%, 20%, 40%, 60%, 80%': {
            transform: 'translateY(0)',
            animationTimingFunction: 'cubic-bezier(0.215, 0.61, 0.355, 1)',
          },
          '40%': { transform: 'translateY(-30px)' },
          '60%': { transform: 'translateY(-15px)' },
        },
        zoomIn: {
          '0%': { opacity: '0', transform: 'scale(0.3)' },
          '50%': { opacity: '1' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
    require('@tailwindcss/aspect-ratio'),
    require('daisyui'),
  ],
  daisyui: {
    themes: ["light"], // Temporalmente usar solo light por defecto para testing
  },
};