name: Domain Provider
form: ~/plugins/aero/clouds/models/domainprovider/fields.yaml
modelClass: Aero\Clouds\Models\DomainProvider
defaultRedirect: aero/clouds/domainproviders
create:
    redirect: aero/clouds/domainproviders/update/:id
    redirectClose: aero/clouds/domainproviders
update:
    redirect: aero/clouds/domainproviders
    redirectClose: aero/clouds/domainproviders
preview:
    redirect: aero/clouds/domainproviders
