# ===================================
#  List Behavior Config
# ===================================

title: Activity Logs
modelClass: Aero\Clouds\Models\ActivityLog
list: $/aero/clouds/models/activitylog/columns.yaml

recordUrl:
recordsPerPage: 50
showPageNumbers: true
defaultSort:
    column: created_at
    direction: desc

toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
        mode: all

filter:
    scopes: $/aero/clouds/models/activitylog/scopes.yaml
