title: Orders
modelClass: Aero\Clouds\Models\Order
list: $/aero/clouds/controllers/orders/columns.yaml
recordUrl: aero/clouds/orders/update/:id
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showPageNumbers: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt

filter:
    scopes:
        status:
            label: Status
            type: group
            conditions: status = :value
            options:
                pending: Pending
                processing: Processing
                completed: Completed
                cancelled: Cancelled
                refunded: Refunded
