list: ~/plugins/aero/clouds/models/domainextension/columns.yaml
modelClass: Aero\Clouds\Models\DomainExtension
title: Domain Extensions
noRecordsMessage: backend::lang.list.no_records
recordUrl: aero/clouds/domainextensions/update/:id
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
filter: config_filter.yaml
